#ifndef CCFWD_H
#define CCFWD_H

/// @file Forward declarations
class action_history;
class action_number;
class board_layout;
class chess_move;
class cc_cli_options;
class delta_t;
class fen_string;
class game;
class game_controller;
class game_coordinate;
class game_options;
class game_rect;
class game_resources;
class game_statistics_widget_layout;
class game_view;
class game_view_layout;
class in_game_time;
class key_bindings;
class layout;
class lobby_options;
class menu_view;
class menu_view_layout;
class message;
class mouse_bindings;
class navigation_controls_layout;
class options_view;
class options_view_layout;
class pgn_game_string;
class pgn_move_string;
class physical_controller;
class physical_controllers;
class piece;
class piece_action;
class piece_id;
class replay;
class screen_coordinate;
class screen_rect;
class sound_effects;
class square;
class textures;
class user_input;
class user_inputs;
class volume;

#endif // CCFWD_H
